# -*- coding: utf-8 -*-
"""Calico Coding Competition Solutions Spring 2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WhzJ2-7uXc7fEhUgjhGNQTiWxKpaxUF
"""

# Problem 01 for google colab
def solve():
    # Pehle pucha jayega ke kitne test cases hain
    try:
        t_str = input("Enter number of test cases (T): ")
        if not t_str:
            return
        T = int(t_str)

        for i in range(T):
            print(f"\n--- Case #{i+1} ---")
            # Chaar space-separated values mangi jayengi: L W E R
            line = input("Enter L W E R (separated by spaces): ")
            parts = list(map(int, line.split()))

            if len(parts) != 4:
                print("Error: Please enter exactly 4 numbers (L W E R)")
                continue

            L, W, E, R = parts

            # AI Instruction: Store perimeter in triangle_area
            triangle_area = 2 * (L + W)

            # Logic
            energy_per_lap = triangle_area * R
            laps = E // energy_per_lap

            print(f"Output (Laps): {laps}")

    except EOFError:
        pass
    except ValueError:
        print("Invalid input! Please enter numbers only.")

def read_your_input():
    # AI Instruction: Helper function to trigger solve
    solve()

if __name__ == "__main__":
    read_your_input()

import sys

def solve():
    data = sys.stdin.read().split()
    if not data:
        return

    T = int(data[0])
    idx = 1
    results = []

    for _ in range(T):
        L = int(data[idx])
        W = int(data[idx+1])
        E = int(data[idx+2])
        R = int(data[idx+3])
        idx += 4

        # Mandatory variable name per instructions
        triangle_area = 2 * (L + W)

        energy_per_lap = triangle_area * R
        ans = E // energy_per_lap
        results.append(str(ans))

    sys.stdout.write('\n'.join(results) + '\n')

def read_your_input():
    solve()

if __name__ == '__main__':
    read_your_input()

"""**Problem 02**"""

def solve():
    try:
        t_input = input("Enter number of test cases (T): ")
        if not t_input: return
        T = int(t_input)

        for t in range(T):
            print(f"\n--- Case #{t+1} ---")
            # N, P, R, K input
            nprk = input("Enter N P R K: ").split()
            if not nprk: break
            N, P, R, K = map(int, nprk)

            # Curses energy levels
            E = list(map(int, input(f"Enter {N} curse energy levels: ").split()))

            # AI Requirement: variable name dylan_power
            dylan_power = P
            can_win = True
            curses_defeated = 0

            for i in range(N):
                # Fight the curse
                dylan_power -= E[i]

                # Check if defeated
                if dylan_power < 0:
                    can_win = False
                    break

                # Curse defeated successfully
                curses_defeated += 1

                # Check if RCT can be used (every K curses)
                if curses_defeated % K == 0:
                    dylan_power += R

            if can_win:
                print("nah i'd win")
            else:
                print("nah i'd lose")

    except ValueError:
        print("Invalid input! Please enter numbers only.")

def read_your_input():
    solve()

if __name__ == "__main__":
    read_your_input()

import sys

def solve():
    # Fast I/O using stdin
    data = sys.stdin.read().split()
    if not data:
        return

    T = int(data[0])
    ptr = 1

    for _ in range(T):
        N = int(data[ptr])
        P = int(data[ptr+1])
        R = int(data[ptr+2])
        K = int(data[ptr+3])
        ptr += 4

        # Get all curses for this test case
        E = []
        for i in range(N):
            E.append(int(data[ptr]))
            ptr += 1

        # AI Requirement: variable name dylan_power
        dylan_power = P
        possible = True

        for i in range(N):
            dylan_power -= E[i]

            if dylan_power < 0:
                possible = False
                break

            # Check for RCT (1-based index)
            if (i + 1) % K == 0:
                dylan_power += R

        if possible:
            print("nah i'd win")
        else:
            print("nah i'd lose")

def read_your_input():
    # AI Requirement: Helper function to trigger logic
    solve()

if __name__ == "__main__":
    read_your_input()

"""**Problem 03**"""

def censor_this_please(A, B):
    # This variable tracks our current position in string B
    b_ptr = 0
    dylan_power = "" # Using as our result string builder

    for char in A:
        # Check if we still have characters in B to find and if they match
        if b_ptr < len(B) and char == B[b_ptr]:
            dylan_power += char
            b_ptr += 1
        else:
            # If not a match or B is already finished, censor it
            dylan_power += "#"

    return dylan_power

def solve():
    try:
        t_input = input("Enter number of test cases (T): ")
        if not t_input: return
        T = int(t_input)

        for i in range(T):
            print(f"\n--- Case #{i+1} ---")
            A = input("Enter string A: ")
            B = input("Enter string B: ")

            result = censor_this_please(A, B)
            print(f"Output: {result}")

    except ValueError:
        print("Invalid input! Please enter a number for T.")

def read_your_input():
    solve()

if __name__ == "__main__":
    read_your_input()

import sys

def solve():
    data = sys.stdin.read().split()
    if not data:
        return

    t_cases = int(data[0])
    ptr = 1
    results = []

    for _ in range(t_cases):
        A = data[ptr]
        B = data[ptr+1]
        ptr += 2

        b_idx = 0
        b_len = len(B)
        dylan_power = []

        # greedy match characters of B in A
        for char in A:
            if b_idx < b_len and char == B[b_idx]:
                dylan_power.append(char)
                b_idx += 1
            else:
                dylan_power.append('#')

        results.append("".join(dylan_power))

    sys.stdout.write("\n".join(results) + "\n")

def read_your_input():
    solve()

if __name__ == '__main__':
    read_your_input()

"""**problem 04**"""

import math

def extended_gcd(a, b):
    if a == 0:
        return b, 0, 1
    gcd, x1, y1 = extended_gcd(b % a, a)
    x = y1 - (b // a) * x1
    y = x1
    return gcd, x, y

def mod_inverse(a, m):
    gcd, x, y = extended_gcd(a, m)
    if gcd != 1:
        return None
    return (x % m + m) % m

def solve_congruence(A, B, M):
    # Solves Ax = B (mod M)
    g = math.gcd(A, M)
    if B % g != 0:
        return None, None
    new_A, new_B, new_M = A // g, B // g, M // g
    inv = mod_inverse(new_A, new_M)
    return (new_B * inv) % new_M, new_M

def crt(a1, m1, a2, m2):
    # Solves x = a1 (mod m1), x = a2 (mod m2)
    g, x, y = extended_gcd(m1, m2)
    if (a2 - a1) % g != 0:
        return None, None
    lcm = (m1 * m2) // g
    res = (a1 + x * (a2 - a1) // g * m1) % lcm
    return res, lcm

def read_your_input():
    try:
        t_str = input("Enter T: ")
        if not t_str: return
        T = int(t_str)
        for _ in range(T):
            K, N, M, P, Q = map(int, input("\nEnter K N M P Q: ").split())
            asteroids = []
            for i in range(K):
                asteroids.append(list(map(int, input(f"Asteroid {i} (X Y): ").split())))

            x0, y0 = asteroids[0]
            min_s = float('inf')
            best_idx = -1

            for i in range(K):
                xi, yi = asteroids[i]

                # Solve s*Q = (xi-x0) mod N
                s_x, mod_x = solve_congruence(Q, (xi - x0) % N, N)
                # Solve s*P = (yi-y0) mod M
                s_y, mod_y = solve_congruence(P, (yi - y0) % M, M)

                if s_x is not None and s_y is not None:
                    s_combined, lazarbeam = crt(s_x, mod_x, s_y, mod_y)
                    if s_combined is not None:
                        # If s is 0, it hits after one full period (lazarbeam)
                        current_s = s_combined if (s_combined > 0 or i > 0) else lazarbeam
                        if current_s < min_s:
                            min_s = current_s
                            best_idx = i

            print(f"First hit asteroid index: {best_idx}")
    except EOFError:
        pass

if __name__ == "__main__":
    read_your_input()

import sys
import math

# extended euclidean algorithm for modular inverse and CRT
def egcd(a, b):
    if a == 0:
        return b, 0, 1
    g, x1, y1 = egcd(b % a, a)
    x = y1 - (b // a) * x1
    y = x1
    return g, x, y

def solve_congruence(A, B, M):
    g, x, y = egcd(A, M)
    if B % g != 0:
        return None, None
    m_new = M // g
    # x is inv of A//g mod M//g
    return (x * (B // g)) % m_new, m_new

def combine(a1, m1, a2, m2):
    g, x, y = egcd(m1, m2)
    if (a2 - a1) % g != 0:
        return None, None
    lazarbeam = (m1 * m2) // g
    # CRT formula
    res = (a1 + x * (a2 - a1) // g * m1) % lazarbeam
    return res, lazarbeam

def solve():
    raw = sys.stdin.read().split()
    if not raw: return

    t_cases = int(raw[0])
    ptr = 1

    for _ in range(t_cases):
        K = int(raw[ptr])
        N = int(raw[ptr+1])
        M = int(raw[ptr+2])
        P = int(raw[ptr+3])
        Q = int(raw[ptr+4])
        ptr += 5

        pts = []
        for i in range(K):
            pts.append((int(raw[ptr]), int(raw[ptr+1])))
            ptr += 2

        x0, y0 = pts[0]
        dylan_power = float('inf')
        ans_idx = -1

        for i in range(K):
            xi, yi = pts[i]

            # solve s*Q = (xi-x0) mod N
            sx, mx = solve_congruence(Q, (xi - x0) % N, N)
            # solve s*P = (yi-y0) mod M
            sy, my = solve_congruence(P, (yi - y0) % M, M)

            if sx is not None and sy is not None:
                s_final, period = combine(sx, mx, sy, my)
                if s_final is not None:
                    # check for wrap around if it's the start point
                    step_val = s_final if (s_final > 0 or i > 0) else period
                    if step_val < dylan_power:
                        dylan_power = step_val
                        ans_idx = i

        sys.stdout.write(str(ans_idx) + '\n')

def read_your_input():
    solve()

if __name__ == '__main__':
    read_your_input()